name: Deploy to Servers

on:
  push:
    branches:
      - develop  # Auto-deploy for staging and development servers on 'develop' branch
  workflow_dispatch: # Manual trigger for production deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HOME_DIR: /home/dev
      REPO_URL: https://github.com/ryannovyansah/Ecommerce-CodeIgniter-Bootstrap.git

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup SSH and Deploy to Development Server
    - name: Setup SSH for Development Server
      if: github.ref == 'refs/heads/develop'
      env:
        SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

    - name: Deploy to Development Server
      if: github.ref == 'refs/heads/develop'
      env:
        SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.DEPLOY_USER }}@$SERVER_IP << EOF
          cd $HOME_DIR
          if [ ! -d "$HOME_DIR/Ecommerce-CodeIgniter-Bootstrap" ]; then
            git clone $REPO_URL
          else
            cd Ecommerce-CodeIgniter-Bootstrap
            git pull origin develop
          fi
        EOF

    # Setup SSH and Deploy to Staging Server
    - name: Setup SSH for Staging Server
      if: github.ref == 'refs/heads/develop'
      env:
        SERVER_IP: ${{ secrets.STAGING_SERVER_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

    - name: Deploy to Staging Server
      if: github.ref == 'refs/heads/develop'
      env:
        SERVER_IP: ${{ secrets.STAGING_SERVER_IP }}
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.DEPLOY_USER }}@$SERVER_IP << EOF
          cd $HOME_DIR
          if [ ! -d "$HOME_DIR/Ecommerce-CodeIgniter-Bootstrap" ]; then
            git clone $REPO_URL
          else
            cd Ecommerce-CodeIgniter-Bootstrap
            git pull origin develop
          fi
        EOF

    # Setup SSH and Deploy to Production Server (Manual Trigger Only)
    - name: Setup SSH for Production Server
      if: github.event_name == 'workflow_dispatch'
      env:
        SERVER_IP: ${{ secrets.PROD_SERVER_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

    - name: Deploy to Production Server
      if: github.event_name == 'workflow_dispatch'
      env:
        SERVER_IP: ${{ secrets.PROD_SERVER_IP }}
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.DEPLOY_USER }}@$SERVER_IP << EOF
          cd $HOME_DIR
          if [ ! -d "$HOME_DIR/Ecommerce-CodeIgniter-Bootstrap" ]; then
            git clone $REPO_URL
          else
            cd Ecommerce-CodeIgniter-Bootstrap
            git pull origin main
          fi
        EOF
